name: orbit
description: SmartCampus Companion — Orbit
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.4.0

  # Secure token storage
  flutter_secure_storage: ^9.0.0

  # Biometric Authentication
  local_auth: ^2.2.0

  # Typography
  google_fonts: ^6.2.1

  # Maps & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  location: ^7.0.1

  # Media & Files
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/announcement_banner.jpg
    - assets/images/event_banner.jpg